import { AppState } from "@/types"

export const seedData: AppState = {
  featureModules: [
    {
      id: "mod-1",
      key: "MOD_DASHBOARD",
      name: "Dashboard",
      description: "Visualização de métricas e KPIs",
      icon: "gauge",
    },
    {
      id: "mod-2",
      key: "MOD_LIVE_CHAT",
      name: "Live Chat",
      description: "Gerenciamento de conversas em tempo real",
      icon: "messages-square",
    },
    {
      id: "mod-3",
      key: "MOD_BASE_CONHECIMENTO",
      name: "Base de Conhecimento",
      description: "Gestão de bases de conhecimento e synapses",
      icon: "book",
    },
    {
      id: "mod-4",
      key: "MOD_PERSONALIZACAO_NEUROCORE",
      name: "Personalização NeuroCore",
      description: "Configuração de agentes de IA",
      icon: "settings",
    },
    {
      id: "mod-5",
      key: "MOD_TREINAMENTO_NEUROCORE",
      name: "Treinamento NeuroCore",
      description: "Teste e treinamento da IA",
      icon: "wand",
    },
  ],

  neurocores: [
    {
      id: "nc-1",
      name: "NeuroCore Varejo",
      description: "NeuroCore especializado em atendimento para varejo",
      niche: "Varejo",
      apiUrl: "https://api.neurocore.example.com/varejo",
      apiSecret: "secret_varejo_123",
      isActive: true,
      associatedAgents: ["agent-1", "agent-2"],
    },
    {
      id: "nc-2",
      name: "NeuroCore Saúde",
      description: "NeuroCore especializado em atendimento para área da saúde",
      niche: "Saúde",
      apiUrl: "https://api.neurocore.example.com/saude",
      apiSecret: "secret_saude_456",
      isActive: true,
      associatedAgents: ["agent-3"],
    },
  ],

  agents: [
    {
      id: "agent-1",
      name: "Agente de Intenções",
      type: "Reativo",
      function: "Atendimento",
      gender: "Feminino",
      persona: "Sou uma assistente virtual amigável e prestativa",
      personalityTone: "Profissional e empático",
      communicationMedium: "WhatsApp",
      objective: "Identificar a intenção do cliente e direcionar para o agente correto",
      instructions: [
        {
          id: "inst-1",
          title: "Saudação Inicial",
          description: "Sempre cumprimente o cliente de forma cordial",
          isActive: true,
          order: 1,
        },
      ],
      limitations: [
        {
          id: "lim-1",
          title: "Não fornecer informações médicas",
          description: "Não dê diagnósticos ou recomendações médicas",
          isActive: true,
          order: 1,
        },
      ],
      conversationRoteiro: [
        {
          id: "rot-1",
          title: "Identificar necessidade",
          mainInstruction: "Pergunte como pode ajudar",
          subTasks: ["Ouvir ativamente", "Fazer perguntas de clarificação"],
          isActive: true,
          order: 1,
        },
      ],
      otherInstructions: [],
      isIntentAgent: true,
      associatedNeuroCores: ["nc-1"],
    },
    {
      id: "agent-2",
      name: "Agente de Vendas",
      type: "Ativo",
      function: "Vendas",
      gender: "Masculino",
      persona: "Sou um consultor de vendas experiente",
      personalityTone: "Confiante e persuasivo",
      communicationMedium: "WhatsApp",
      objective: "Converter leads em vendas",
      instructions: [],
      limitations: [],
      conversationRoteiro: [],
      otherInstructions: [],
      isIntentAgent: false,
      associatedNeuroCores: ["nc-1"],
    },
    {
      id: "agent-3",
      name: "Agente Pós-Venda",
      type: "Reativo",
      function: "Pós-Venda",
      gender: "Feminino",
      persona: "Sou especialista em atendimento pós-venda",
      personalityTone: "Atencioso e solucionador",
      communicationMedium: "WhatsApp",
      objective: "Garantir satisfação do cliente após a compra",
      instructions: [],
      limitations: [],
      conversationRoteiro: [],
      otherInstructions: [],
      isIntentAgent: false,
      associatedNeuroCores: ["nc-2"],
    },
  ],

  tenants: [
    {
      id: "tenant-1",
      name: "Loja Tech Store",
      neurocoreId: "nc-1",
      isActive: true,
      cnpj: "12.345.678/0001-90",
      phone: "+55 11 98765-4321",
      responsibleTech: {
        name: "Carlos Silva",
        whatsapp: "+55 11 98765-1111",
        email: "carlos@techstore.com",
      },
      responsibleFinance: {
        name: "Maria Santos",
        whatsapp: "+55 11 98765-2222",
        email: "maria@techstore.com",
      },
      plan: "Premium",
    },
    {
      id: "tenant-2",
      name: "Clínica Vida Saudável",
      neurocoreId: "nc-2",
      isActive: true,
      cnpj: "98.765.432/0001-10",
      phone: "+55 21 97654-3210",
      responsibleTech: {
        name: "João Pedro",
        whatsapp: "+55 21 97654-1111",
        email: "joao@vidasaudavel.com",
      },
      responsibleFinance: {
        name: "Ana Costa",
        whatsapp: "+55 21 97654-2222",
        email: "ana@vidasaudavel.com",
      },
      plan: "Business",
    },
    {
      id: "tenant-3",
      name: "Empresa Inativa",
      neurocoreId: "nc-1",
      isActive: false,
      cnpj: "11.222.333/0001-44",
      phone: "+55 11 91111-2222",
      responsibleTech: {
        name: "Pedro Oliveira",
        whatsapp: "+55 11 91111-3333",
        email: "pedro@inativa.com",
      },
      responsibleFinance: {
        name: "Julia Lima",
        whatsapp: "+55 11 91111-4444",
        email: "julia@inativa.com",
      },
      plan: "Basic",
    },
  ],

  users: [
    {
      id: "user-admin",
      tenantId: null,
      fullName: "Admin Super",
      email: "admin@livia.com",
      whatsappNumber: "+55 11 99999-9999",
      role: "super_admin",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
      modules: [],
      lastSignInAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: "user-1",
      tenantId: "tenant-1",
      fullName: "Roberto Costa",
      email: "roberto@techstore.com",
      whatsappNumber: "+55 11 98765-5555",
      role: "usuario_cliente",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto",
      modules: [
        "MOD_DASHBOARD",
        "MOD_LIVE_CHAT",
        "MOD_BASE_CONHECIMENTO",
        "MOD_PERSONALIZACAO_NEUROCORE",
        "MOD_TREINAMENTO_NEUROCORE",
      ],
      lastSignInAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: "user-2",
      tenantId: "tenant-1",
      fullName: "Fernanda Alves",
      email: "fernanda@techstore.com",
      whatsappNumber: "+55 11 98765-6666",
      role: "usuario_cliente",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda",
      modules: ["MOD_DASHBOARD", "MOD_LIVE_CHAT"],
      lastSignInAt: null,
      isActive: true,
    },
    {
      id: "user-3",
      tenantId: "tenant-2",
      fullName: "Dr. Ricardo Mendes",
      email: "ricardo@vidasaudavel.com",
      whatsappNumber: "+55 21 97654-7777",
      role: "usuario_cliente",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo",
      modules: [
        "MOD_DASHBOARD",
        "MOD_LIVE_CHAT",
        "MOD_BASE_CONHECIMENTO",
      ],
      lastSignInAt: new Date().toISOString(),
      isActive: true,
    },
  ],

  contacts: [
    {
      id: "contact-1",
      tenantId: "tenant-1",
      name: "José da Silva",
      phone: "+55 11 91234-5678",
      phoneSecondary: null,
      email: "jose@email.com",
      country: "Brasil",
      city: "São Paulo",
      zipCode: "01310-100",
      addressStreet: "Av. Paulista",
      addressNumber: "1000",
      addressComplement: "Apto 101",
      cpf: "123.456.789-00",
      rg: "12.345.678-9",
      lastInteraction: new Date().toISOString(),
      status: "Com IA",
      customerDataExtracted: {},
      tags: ["vip", "recorrente"],
      lastNegotiation: {
        produto: "Notebook Dell",
        valor: 3500,
        status: "Em negociação",
      },
    },
    {
      id: "contact-2",
      tenantId: "tenant-1",
      name: "Maria Oliveira",
      phone: "+55 11 92345-6789",
      phoneSecondary: "+55 11 3333-4444",
      email: "maria@email.com",
      country: "Brasil",
      city: "São Paulo",
      zipCode: "04543-907",
      addressStreet: "Rua dos Pinheiros",
      addressNumber: "500",
      addressComplement: null,
      cpf: "987.654.321-00",
      rg: null,
      lastInteraction: new Date(Date.now() - 3600000).toISOString(),
      status: "Pausada",
      customerDataExtracted: {},
      tags: ["novo"],
      lastNegotiation: null,
    },
  ],

  conversations: [
    {
      id: "conv-1",
      contactId: "contact-1",
      tenantId: "tenant-1",
      status: "Conversando",
      iaActive: true,
      lastMessageAt: new Date().toISOString(),
      overallFeedback: null,
    },
    {
      id: "conv-2",
      contactId: "contact-2",
      tenantId: "tenant-1",
      status: "Pausada",
      iaActive: false,
      lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
      overallFeedback: null,
    },
  ],

  messages: [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderType: "customer",
      senderId: null,
      content: "Olá, gostaria de saber sobre notebooks",
      timestamp: new Date(Date.now() - 600000).toISOString(),
      feedback: null,
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderType: "ia",
      senderId: "agent-1",
      content:
        "Olá! Seja bem-vindo à Tech Store! Claro, ficarei feliz em ajudar com notebooks. Você está procurando para qual finalidade? Trabalho, estudos ou jogos?",
      timestamp: new Date(Date.now() - 540000).toISOString(),
      feedback: {
        type: "like",
        text: "Resposta muito educada",
      },
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderType: "customer",
      senderId: null,
      content: "Para trabalho, preciso de algo potente",
      timestamp: new Date(Date.now() - 480000).toISOString(),
      feedback: null,
    },
    {
      id: "msg-4",
      conversationId: "conv-1",
      senderType: "ia",
      senderId: "agent-2",
      content:
        "Perfeito! Para trabalho, temos ótimas opções. Recomendo o Dell Inspiron 15 com Intel i7, 16GB RAM e SSD 512GB por R$ 3.500,00. Também temos o Lenovo ThinkPad por R$ 4.200,00. Qual você prefere?",
      timestamp: new Date(Date.now() - 420000).toISOString(),
      feedback: null,
    },
  ],

  baseConhecimento: [
    {
      id: "base-1",
      tenantId: "tenant-1",
      name: "Base Produtos Tech Store",
      description: "Informações sobre produtos eletrônicos",
      neurocoreId: "nc-1",
      isActive: true,
    },
    {
      id: "base-2",
      tenantId: "tenant-2",
      name: "Base Procedimentos Clínica",
      description: "Procedimentos e tratamentos oferecidos",
      neurocoreId: "nc-2",
      isActive: true,
    },
  ],

  synapses: [
    {
      id: "syn-1",
      baseConhecimentoId: "base-1",
      tenantId: "tenant-1",
      title: "Notebooks Dell",
      description:
        "Linha completa de notebooks Dell com especificações técnicas e preços",
      imageUrl: null,
      status: "PUBLICANDO",
    },
    {
      id: "syn-2",
      baseConhecimentoId: "base-1",
      tenantId: "tenant-1",
      title: "Política de Garantia",
      description: "Informações sobre garantia e trocas de produtos",
      imageUrl: null,
      status: "RASCUNHO",
    },
    {
      id: "syn-3",
      baseConhecimentoId: "base-2",
      tenantId: "tenant-2",
      title: "Consultas Médicas",
      description: "Tipos de consultas e especialidades disponíveis",
      imageUrl: null,
      status: "PUBLICANDO",
    },
  ],

  feedbacks: [
    {
      id: "feed-1",
      tenantId: "tenant-1",
      userId: "user-1",
      conversationId: "conv-1",
      messageId: "msg-2",
      feedbackType: "like",
      feedbackText: "Resposta muito educada e prestativa",
      feedbackStatus: "Em Aberto",
      superAdminComment: null,
      createdAt: new Date(Date.now() - 540000).toISOString(),
    },
    {
      id: "feed-2",
      tenantId: "tenant-1",
      userId: "user-1",
      conversationId: "conv-2",
      messageId: null,
      feedbackType: "dislike",
      feedbackText:
        "A IA demorou muito para responder e deu informações incorretas",
      feedbackStatus: "Sendo Tratado",
      superAdminComment: "Vamos revisar o tempo de resposta do agente",
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],

  quickReplyTemplates: [
    {
      id: "qr-1",
      tenantId: "tenant-1",
      title: "Saudação",
      message: "Olá! Como posso ajudá-lo hoje?",
      icon: "👋",
      usageCount: 50,
    },
    {
      id: "qr-2",
      tenantId: "tenant-1",
      title: "Agradecimento",
      message: "Obrigado por entrar em contato! Estamos à disposição.",
      icon: "🙏",
      usageCount: 35,
    },
    {
      id: "qr-3",
      tenantId: "tenant-1",
      title: "Horário de Atendimento",
      message:
        "Nosso horário de atendimento é de segunda a sexta, das 9h às 18h.",
      icon: "🕐",
      usageCount: 20,
    },
  ],

  currentUser: null,

  globalFilters: {
    period: "30d",
    conversationSelection: "all",
  },
}

